5.0.3 - Bug fixes.
registry.py:
BUG01: Error 'ImportError: cannot import name ui' thrown when importing
EHM.enviro
FIX01: As of utils v5.0.2, the ui class instantiation shortcut has been
removed from the utils.user_interface.UserInterface() class.
Updated the user_interface import to: import user_interface as ui;
then instantiate the class.

user_interface.py:
BUG03: When analysing EHM.enviro with pylint, this error
was caught: '_Client._set_type: No value for argument 'text' in method
call'
On inspection, the utils.user_interface.print_error_enviro method
requires a 'text' argument.
FIX03: The text argument is old/residual code and have been removed as
the text for this error is pulled form the config file.